Bar top scene
TheWazzzzzup/We-Are-Drunk pull request #7
Opened 2023-06-04 08:09 UTC by TheWazzzzzup

forgot to pr

2023-06-04 08:09 UTC, TheWazzzzzup commented
@GDIVX review : )

2023-06-04 16:09 UTC, GDIVX requested changes

2023-06-04 16:09 UTC, GDIVX commented on Assets/Scripts/CounterTop/IngredientSpawnArea.cs
> +#region OldCodeToRefer
please remove

2023-06-05 15:26 UTC, TheWazzzzzup commented
@GDIVX
did it left it for you to confirm

2023-06-05 15:27 UTC, merged